rsyslog/librelp

- configure.ac
- src/relpsess.c
- src/tcp.c
Also prepared for next librelp release
> debug: Fixed invalid debug assert checks in tls functions

- src/librelp.h
- src/relpclt.c
- src/relpclt.h
- src/relpsess.c
- src/relpsess.h
- src/tcp.c
- src/tcp.h
Allows for setting a connection timeout with a default of 10 seconds
> Configurable connection timeout

- src/Makefile.am
- src/librelp.h
- src/relpclt.c
- src/relpclt.h
- src/relpsess.c
- src/relpsess.h
- src/tcp.c
- src/tcp.h
includes everything needed to finally merge #33
> Merge PR #33

- src/tcp.c
commit d0326b63e56fcdefbf3d97833edf32bcba669eae was incomplete
and did not cover some places where high-numbered fd's caused
problems in select. This fixes those remaining issues.
see also #38
> fix potential segfault when high-numbered fd is used in sender

- src/tcp.c
merge PR #23 plus some needed adjustments
> Merge PR #23

- .travis.yml
- CI/check_codestyle.sh
- Makefile.am
- devtools/check-codestyle.sh
- devtools/default_dev_container
- devtools/devcontainer.sh
- devtools/run-configure.sh
- devtools/run-static-analyzer.sh
- devtools/travis-run-compile-tests.sh
- src/relp.c
- src/relpframe.c
includes some fixes for "new" compiler warnings
> improve CI via rsyslog development container

- ChangeLog
- src/tcp.c
running this through CI to test CI a bit more...
> maintain ChangeLog

- src/tcp.c
this at least leads to better error messages
detected by Coverity Scan
CIDs: 274517, 266019, 266012, 266011, 266010
> fix unchecked results in OS calls

- configure.ac
- src/Makefile.am
- tests/Makefile.am
closes https://github.com/rsyslog/librelp/issues/2
> build system: do not overwrite CFLAGS

- .travis.yml
- devtools/check-codestyle.sh
- devtools/devcontainer.sh
- devtools/run-static-analyzer.sh
- tests/CI/solaris-findport.sh
- tests/duplicate-receiver-vg.sh
- tests/tls-basic-vg.sh
detected by shellcheck (via CodeFactor)
> fix bash nits

- tests/receive.c
- tests/test-framework.sh
also, receiver process now cleanly writes into specified file instead
of stdout (which is problematic as we may get unrelated messages
there).
> testbench: modernize and extend framework a bit

- .codecov.yml
- tests/Makefile.am
- tests/basic-realistic.sh
- tests/send.c
- tests/test-framework.sh
so far, only single messages were transmitted during testing. While
this is nice to check some basic features, it for sure is not sufficient
to detect many failure conditions.
This commit adds a first test which sends a larger number of messages
(50000 right now) and also extends the testbench framework with support
for this.
> testbench: add realistic test with multiple messages sent

- src/relpsess.c
multiple open commands can happen when a session was broken
and is being reestablished. Chances to experience this problem
increase with the number of sessions broken in a row. A trigger
is that the remote system accepts the TCP connection, but does
NOT send a response to the "open" command (aka "very short-lived
session).
Note that commit 12392015d4f8e99d6226ab827beb0b7836050efb tried
to "fix" this on the server side. Testing shows this is not possible.
That commit will be reverted soon.
This patch here fixes the root cause.
closes https://github.com/rsyslog/librelp/issues/129
> bugfix: do not send multiple open commands

- devtools/travis-run-compile-tests.sh
- src/relpclt.c
- src/relpsrv.c
> fix minor issues

- configure.ac
- src/copen.c
- src/relpsess.c
- src/scrsp.c
- src/tcp.c
- tests/Makefile.am
- tests/basic-realistic.sh
- tests/chkseq.c
- tests/dummyserver.py
- tests/receive.c
- tests/receiver-abort.sh
- tests/send.c
- tests/test-framework.sh
also change testbench framework to support this
imported rsyslog tool "chkseq" for checking
> testbench: add test for receiver abort and restart

- configure.ac
- src/librelp.h
- src/relp.c
- src/relp.h
- src/tcp.c
- src/tcp.h
- tests/Makefile.am
- tests/duplicate-receiver-vg.sh
- tests/have_tlslib.c
- tests/receive.c
- tests/send.c
- tests/test-framework.sh
- tests/tls-basic-anon.sh
- tests/tls-basic-certvalid.sh
- tests/tls-basic-fingerprint.sh
- tests/tls-basic-realistic.sh
- tests/tls-basic-vg.sh
- tests/tls-basic-wildcard.sh
- tests/tls-missing-param-receiver.sh
- tests/tls-wrong-permittedPeer.sh
- tests/tls-wrong-signedcert.sh
**This provides API extensions --> update soname**
This most probably should go into 1.4.0!
> Permit librelp to use both TLS drivers in parallel

- src/tcp.c
- tests/tls-basic-vg.sh
> fix cert auth in openssl mode

- src/relp.c
- src/relpsess.c
- src/tcp.c
- tests/send.c
> fix some nits in C code

- devtools/check-codestyle.sh
- devtools/default_dev_container
- devtools/run-static-analyzer.sh
- devtools/travis-run-compile-tests.sh
- src/relpsess.c
- tests/receive.c
- Fixed issue in relpsess found using clang (Possible dupl of NULL
string).
- Fixed issue found in gcc build in receive.c (variable initialization).
- Exclude generated config.h from codestyle check
> testbench: Fixed / updated travis test script

- tests/Makefile.am
closes: https://github.com/rsyslog/librelp/issues/206
> distcheck: add missing cert files from PR #196

- configure.ac
- tests/Makefile.am
- tests/receive-emptyconnect.sh
- tests/set-envvars.in
- tests/test-framework.sh
closes: https://github.com/rsyslog/librelp/issues/214
> testbench: obtain python binary path via AM_PATH_PYTHON

- src/tcp.c
When more than one librelp instance are used in the same process,
and the relpTcpExitTLS call was called a second time, the process
could freeze due a double free (See SSL_CTX_free call).
Thanks to David GOUARIN <david.gouarin@thalesgroup.com> for the
discovery and initial fix.
Also added an openssl instance counter to avoid freeing the SSL library
which could be still in use by another librelp instance
in the same process.
closes: #235
> openssl: fix openssl exit code avoid double free of ctx

- src/tcp.c
- OpenSSL error strings are loaded automatically now
- Adapted Debug Callback for 3.x
- See for more: https://www.openssl.org/docs/manmaster/man7/migration_guide.html
closes: https://github.com/rsyslog/librelp/issues/246
> OpenSSL: fix depreacted API issues for OpenSSL 3.x
