rsyslog/librelp

src/relp.c, src/relpsess.c
We ignore the return state now because otherwise we will
lose the whole relp frame buffer. This happens when the
remote client closes the connection before the frame has
been processed on the server side. Relp send functions also
have to check for broken sessions now.
Also added error handling in relpSessWaitState function
=> commands: Ignoring the return state in syslog command handler

src/relpsess.c
When sending large buffers it's possible that only part of buffer data
will be transferred before connection is closed. Then on connection
re-establishing librelp thinks part of buffer is already sent and
transfers only remaining part. Remote side then is not be able to parse
such message and always closes the connection.
Fix this by resetting bufPtr in relpSendbuf_s before re-sending unacked
message.
Initially I've encountered this problem in rsyslog, one instance was
publishing large messages (~32k) to another via TLS connections with TLS
compression enabled and there were constant disconnects after first
connection reestablishing, all because of that partial buffer sending.
=> Send full buffers after connection re-establishing

src/relpframe.h, src/relpsess.c
Ran into an issue today where the connection to a relp server was severed before a proper frame was received by the client.
Attaching `gdb` to the process showed that `omrelp` was stuck trying to re-establish the session while the recv frame state machine was in `eRelpFrameRcvState_IN_TRAILER`
This was bad since when trying to re-establish the session, offers are sent and expected to be received by the client. Ideally `pCurrRcvFrame` on the session is null, allowing `relpFrameProcessOctetRcvd` to create a new `relpFrame_t`, and then properly process the relp server offers.
=> Flush the current recv frame if it exists if the client session is restarting

src/librelp.h, src/relpclt.c, src/relpclt.h, src/relpsess.c, src/relpsess.h, src/tcp.c, src/tcp.h
Reverts rsyslog/librelp#29
When applied, this patch casuses TLS connections to fail. This is visible when used together with rsyslog's testbench. Test ```sndrcv_relp_tls.sh``` then returns theses results:
```
------------------------------------------------------------
Test: ./sndrcv_relp_tls.sh
------------------------------------------------------------
rsyslogd started with pid  86613
rsyslogd started with pid  86613
rsyslogd: imrelp[13515]: error 'TLS handshake failed [gnutls error -15: An unexpected TLS packet was received.]', object  'lstn 13515: conn to clt 127.0.0.1/localhost' - input may not work as intended [v8.19.0.master try http://www.rsyslog.com/e/2353 ]
rsyslogd: imrelp[13515]: error 'TLS record write failed [gnutls error -10: The specified session has been invalidated for …
```
=> Revert "Configurable connection timeout"

configure.ac, src/relpsess.c
When a fd (socket) with value >= 1024 was used by the client sender
process, the library could segfault in select(). This depended a bit
on the platform.
This patch solves the issue by replacing the select() call with
poll(). Note that we do not changed to epoll(), because
(a) we only wait on a single fd
(b) poll() is more portable
closes https://github.com/rsyslog/librelp/issues/38
=> fix potential segfault when high-numbered fd is used in sender

src/copen.c, src/librelp.h, src/relpsess.h
closes https://github.com/rsyslog/librelp/issues/37
=> bugfix: do not accept more than one "open" verb on a connection

src/librelp.h, src/relpclt.c, src/relpclt.h, src/relpsess.c, src/relpsess.h, src/tcp.c, src/tcp.h
Turning the socket back to blocking before performing the tls handshake fixed the test failures.
This should make rsyslog/rsyslog#1023 viable for merging
=> Configurable connection timeout

src/relpsess.c
Hello
This fixes #47 
relpSessWaitState is used by relpSessSendCommand to check server responses. Unfortunately, the step where the socket is read is actually never reached because of an early exit path introduced by commit f9d9b263500eb8b8ce65d440a103fdad597146d6. So the RELP client piles up unacked messages.
Also the client doesn't notice immediately that the socket is broken after server restart because it never gets the serverclose command.
After reverting this commit, the client processes the server response of last message before sending subsequent messages, so the unacked list stays up-to-date and there is no more duplicates after connection restart. Moreover it makes rsyslog able to handle serverclose commands.
dud
=> Fix duplicate lines after rsyslog-server restart

.travis.yml, src/copen.c
The "connection already open" error message when trying to open
an already open connection was truncated due to too-small size
specified.
Thanks to rsyslog formum user AlanR for the problem report.
=> bugfix: error message on session open is truncated

src/relpsess.c
this for should should not have been an assignment
thanks to github user KatMisato for alerting us
fixes https://github.com/rsyslog/librelp/issues/66
=> fix invalid assert predicate

src/tcp.c
This is very unlikely to occur in practice. Memory can be leaked
when TLS initialization fails when the client tries to connect
to the server. However, if this actually happens, it can happen
frequently and so accumulate to a large leak.
No report of such occurence from practice.
Detected by Coverity Scan, CID 266008.
=> fix a potential memory leak

src/relpsess.c
Hi author.
I fixed memory leak when protocol error occurred, related #59, #60.
Please review.
relpFrame_t allocated in relpFrameProcessOctetRcvd and associated to relpSess_t.pCurrRcvFrame is released with the internal state eRelpFrameRcvState_IN_TRAILER.
But if session deletion processing is done for some reason before this state, relpSess_t.pCurrRcvFrame will not be released and a memory leak will occur.
- tested with #59 attached script.
not patched
```
==1429== HEAP SUMMARY:
==1429==     in use at exit: 67,528,403,558 bytes in 1,299 blocks
==1429==   total heap usage: 11,471 allocs, 10,172 frees, 67,529,222,909 bytes allocated
==1429==
==1429== 11,324,620,800 bytes in 27 blocks are possibly lost in loss record 9 of 11
==1429==    at 0x4C2AB80: malloc (in …
```
=> Fixed memory leak when protocol error occurred.

src/relpframe.c
Moved payload length check before actual buffer allocation in case reported payload length is greater than configured limit to disable unnecessary memory allocations.
Related to: #59
=> Moved check for payload length before buffer allocation.

configure.ac
Valgrind will now only used when explicitly requested via "--enable-valgrind" configure switch. Therefore, if requested but valgrind isn't available, configure will fail with an error.
Fixes: 88600be7bb55 ("testbench: valgrind can be disabled in configure")
Fixes: https://github.com/rsyslog/librelp/issues/100
=> configure: Fix valgrind usage

src/tcp.c
When calling the registered OnErr function for errors caused by connect
failing, include the underlying socket error.
This is related to the https://github.com/rsyslog/rsyslog/issues/2793 that I reported yesterday.
=> include underlying socket error in call to OnErr

src/relp.c, src/relp.h, src/tcp.c
see also https://github.com/rsyslog/librelp/pull/106
closes https://github.com/rsyslog/librelp/issues/108
=> replace strerror() by portable equivalent

src/Makefile.am
closes https://github.com/rsyslog/librelp/issues/99
=> do not expose symbols that are not part of public API

src/librelp.h, src/sendbuf.c, src/sendq.c
It's not clear whether we're going to continue using imrelp at Fastly, but this should fix the bug discussed in #13.
fixes https://github.com/rsyslog/librelp/issues/13
=> handle EAGAIN properly

tests/Makefile.am, tests/duplicate-receiver-vg.sh
In rsyslog configuring two identical relp receiver leads
to an error. The test checks that everything is working
fine within librelp.
See: https://github.com/rsyslog/rsyslog/issues/2874
=> add test for duplicate receiver error

src/tcp.c
Fix below jump-misses-init error
| In file included from ../../git/src/tcp.c:51:
| ../../git/src/tcp.c: In function 'relpTcpConnect':
| ../../git/src/relp.h:220:3: error: jump skips variable initialization [-Werror=jump-misses-init]
|    goto finalize_it;  \
|    ^~~~
| ../../git/src/tcp.c:3040:3: note: in expansion of macro 'ABORT_FINALIZE'
|    ABORT_FINALIZE(RELP_RET_IO_ERR);
|    ^~~~~~~~~~~~~~
| ../../git/src/tcp.c:3096:1: note: label 'finalize_it' defined here
|  finalize_it:
|  ^~~~~~~~~~~
| ../../git/src/tcp.c:3083:6: note: 'r' declared here
|   int r = getsockopt(pThis->sock, SOL_SOCKET, SO_ERROR, &so_error, &len);
|       ^
| In file included from ../../git/src/tcp.c:51:
| ../../git/src/relp.h:220:3: error: jump skips variable initialization [-Werror=jump-misses-init]
|    goto …
=> src/tcp.c: fix jump-misses-init error

src/tcp.c
Increase the size of szHname to fix below
error:
| ../../git/src/tcp.c: In function 'relpTcpSetRemHost':
| ../../git/src/tcp.c:887:57: error: '%s' directive output may be truncated writing up to 1024 bytes into a region of size 1011 [-Werror=format-truncation=]
|      snprintf((char*)szHname, NI_MAXHOST, "[MALICIOUS:IP=%s]", szIP);
|                                                          ^~    ~~~~
| In file included from /poky-build/tmp/work/i586-poky-linux/librelp/1.2.16-r0/recipe-sysroot/usr/include/stdio.h:862,
|                  from ../../git/src/tcp.c:38:
| /poky-build/tmp/work/i586-poky-linux/librelp/1.2.16-r0/recipe-sysroot/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 16 and 1040 bytes into a destination of size 1025
|    return …
=> src/tcp.c: increase the size of szHname

src/tcp.c
We cannot use a fixed number for NI_HOSTNAME, as this may be different
on different platforms. But we know how much data we add, so we can
increase the value accordingly.
=> fix commit dd59c925ec631a4e1cfa082c76a30de30908ca14

src/copen.c
librelp sometimes sends multiple open commands WITHIN the open
session, intermixed with app-layer data. As of the relp spec,
this leads to session closure. However, we have relaxed this
so that the multiple opens are ignored, as that "feature"
caused quite some trouble in practice.
That said, the client part of librelp should also be fixed to
not send multiple open commands any longer. However, we must
expect that old versions will exist for years, so we really
need to handle this at the server level.
Special thanks to github user perlei for proposing the base
idea for this fix (it just needed small adjustments).
see also https://github.com/rsyslog/librelp/issues/129
=> gracefully handle multiple open commands

src/relpsess.c
Adding error messages at very important places. While code
is far from perfect, this is very useful and should go into
the mail line ASAP. Will improve in follow-on commits.
see also https://github.com/rsyslog/librelp/issues/130
=> emit more error messages, first increment

src/copen.c
Commit 1deb7c6936a539ee16d13867e6f1cafa5286491f tried to handle
multiple open commands gracefully in the hope to enable new servers
to handle (faulty) old clients. Unfortunately, this did not work
out as the client became stuck inside it's state machine. The way
the client code is structured, it cannot advance from INIT_DONE
to READY_TO_SEND. As the whole point of the relaxed condition was
to avoid client changes, the idea does not make any sense.
Instead 1deb7c6936a539ee16d13867e6f1cafa5286491f has fixed the
root cause, and so we can keep strict, just as the RELP spec
requires us.
=> be strict with multiple open commands

tests/Makefile.am, tests/receive.c, tests/selftest_receive_watchdog.sh
We now have a watchdog timer which auto-terminates itself after
60 secs (default) of activity. So this cannot hang on the CI, which
also means we do not need to cancel it out.
Other tools may need similar enhancement (to be checked).
=> testbench: ensure "receive" tool cannot hang

tests/dummyclient.py
This small fix should make dummyclient.py support both, Python2 and Python3.
=> tests: make dummyclient.py compatible with Python2 and Python3

tests/receiver-abort.sh, tests/test-framework.sh, tests/tls-receiver-abort.sh
some tests require special OS commands, and cannot be run when they
are not available. This lead to false positives.
=> testbench: ensure tests run only when possible

src/relp.c
I'm building this on an old system (Debian Wheezy, gcc 4.7.2) so it's not all that surprising that this bug has existed for 6 years. The 'emsg' variable comes from the above function so just some copy/paste error.
Prior to fix:
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -pthread -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -c -o librelp_la-relp.lo `test -f 'relp.c' || echo './'`relp.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -pthread -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -Wformat-security -Wshadow …
```
=> Variable undefined fix for when HAVE_STRERROR_R is defined

configure.ac
closes https://github.com/rsyslog/librelp/issues/169
=> build system fix: invalid default in configure help text

src/librelp.h, src/relpclt.c, src/relpclt.h, src/relpsess.c, src/relpsess.h, src/relpsrv.c, src/relpsrv.h, src/tcp.c, src/tcp.h, tests/Makefile.am, tests/receive.c, tests/send.c, tests/test-framework.sh, tests/tls-basic-tlscommand.sh
Add two API calls to set SSL_CONF_cmd properties:
- relpCltSetTlsConfigCmd
- relpSrvSetTlsConfigCmd
cfgcmd is used to pass configuration commands to openssl.
The format is one command per line, command and value separated by equal sign (=).
See this sample:
"command=value
secondcommand=value"
=> Add support for using SSL_CONF_cmd API (openssl)

src/relpsess.c
When librelp is instructed to shutdown, it processes messages
still present inside its receive buffers. It only terminates
when it needs to wait for new data to arrive.
Depending on RELP and TCP window size and message length,
this may cause many messages to be processed while in shutdown.
Even with default settings, up to 128 messages may be taken off
the wire and be processed.
This is a problem regarding the shutdown timing of a librelp
user (e.g. rsyslog). It may take unexpectedly long to shutdown
the RELP component and as such timeout may occur in the caller
code. This is especially the case if the caller does lengthy
processing when a RELP message is received. Note: It is
perfectly fine for a caller to do this. The problem is that
librelp continues to provide new data for a …
=> bugfix: too late termination of relp Engine on shutdown

src/tcp.c, tests/receive.c, tests/send.c
this already happens with TLS, but not with plain tcp. Error messages
are a useful troubleshooting tool.
=> report io errors for plain tcp connections

src/relpsess.c
In iRet handler of relpSessSendResponse, the sendbuf
was freed if iRet returned a failure.
However if error RELP_RET_IO_ERR happened in relpSendqAddBuf,
sendbuf was already assigned to relpSendqe_t. As a result
sendbuf was double freed in relpSendqDestruct.
see also
https://github.com/rsyslog/rsyslog/issues/4184
https://github.com/rsyslog/rsyslog/issues/4005
closes https://github.com/rsyslog/librelp/issues/183
=> replsess: fix double free of sendbuf in some cases.

src/tcp.c
With this I can build librelp on OpenBSD where LibreSSL is the default.
=> LibreSSL has no support for @SECLEVEL and SSL_CONF_CTX_set_flags().

src/tcp.c
Edited TLS priority string default to conform to system-wide default
and align librelp behavior with other crypto-utilizing packages
=> Modified GnuTLS priority according to standard crypto-policy guideline

src/Makefile.am
Librelp exported some functions related to the internal driver API. This
was not desired and is fixed with this commit. We assume, and require
from now on, that driver functions contain an underscore "_" in their
name. This is how they are already named.
closes https://github.com/rsyslog/librelp/issues/179
=> build system: do not export librelp internal driver APIs

src/sendq.c, tests/Makefile.am, tests/basic-sessionbreak-vg.sh, tests/receive.c, tests/send.c, tests/test-framework.sh
When librelp session breaks unexpected, a memory leak could happen in sendq.c
when relpSendqeConstruct was called before the session break happened.
- Also Adds a new valgrind test basic-sessionbreak-vg.sh to reproduce
the problem. without the fix, the test will fail.
- Adjusted testbench plumbing to support session break valgrind test.
=> fix memory leak on session break.

src/relp.c, src/tcp.c, src/tcp.h
For a clean cleanup, OpenSSL remains are now being removed at the end
of relpEngineDestruct()
closes: https://github.com/rsyslog/librelp/issues/199
=> TLS: Added call to destruct OpenSSL remains to relpEngineDestruct

src/tcp.c
AWS LB has timeouts when connection is inactive and when this happens, AWS LB shuts down socket from one-side only. When rsyslog detects one-sided shutdown, it assumes that connection is closed while it isn't. The connection is left unclosed and unclosed FD are piling up, eventually filling up FD number space.
Removing the assignment to -1 allows rsyslog to close the connection later.
=> Fix FD leak when socket shutdown is one-sided

devtools/devcontainer.sh, src/tcp.c, tests/tls-basic-certchain.sh
For older OpenSSL Versions, we are loading the Own Certfile
(Which can be chained) into CTX Verify locations. This enables
chained certificates for older OpenSSL Versions as well
devtools: updated devcontainer.sh (based on rsyslog version)
see also: https://github.com/rsyslog/librelp/issues/195
=> openssl: Fix chained certificate files for older OpenSSL Version.

src/Makefile.am, src/relp.c, src/relp.h, src/relpclt.c, src/relpsrv.c
closes https://github.com/rsyslog/librelp/issues/187
=> bugfix: library did export non-API symbols

src/relp.c, src/relpclt.c, src/relpsrv.c
Thanks to Michael Biebl for pointing this out.
see also: https://github.com/rsyslog/librelp/issues/187#issuecomment-680974232
=> exported symbol bugfix: still some non-API functions were exported

src/tcp.c
In relpTcpDestructTLS_gtls which fixes a memory leak in gnutls driver.
closes: https://github.com/rsyslog/librelp/issues/194
=> gnutls: added call for gnutls_certificate_free_credentials

src/tcp.c
Some TLS servers don't reply to graceful shutdown requests "for
optimization". This can lead to librelp keeping the connection
for ever and thus effectively to hang on it.
This patch is modelled after a simuilar patch by Renaud Métrich
for rsyslog.
see also https://github.com/rsyslog/rsyslog/pull/4424
=> gnutls "bugfix": handle receives who break connection on close

configure.ac, src/Makefile.am, src/compat/strndup.c, src/relp.h, src/tcp.c, tests/test-framework.sh, tests/tls-basic-tlscommand.sh
tls config commands no is compiled for OpenSSL 1.0.2.
closes: https://github.com/rsyslog/librelp/issues/221
=> openssl: fix preprocessor check for tlsconfigcmd code

src/offers.c, src/tcp.c, tests/Makefile.am, tests/tls-basic-tlscommand-ciphers.sh
When the client tried to conntect to the server, custom cipherstrings (Set by tlscommands feature) were not used. This could lead to the negotiation of different and potentially weaker ciphers. Other custom tlscommands settings like Protocol where not affected. We do not overwrite the custom ciphers anymore if they are set by tlscommands. Another problem only related to the relp receiver (server) was, that the custom tlscommands/priority string where not applied on the accepted client connections. This could lead to the same problem as the default ciphers were used.
Besides the main problem, the following changes were applied:
- Add new testcase for setting custom tls ciphers in tlscommand.
- Add support to use semicolon (;) as tlscommand seperator (See new testcase)
- Fix GCC9 …
=> openssl: Fix tlscommand support for ciphers.

.github/workflows/rsyslog.yml, tests/Makefile.am, tests/basic-sessionbreak-vg.sh, tests/duplicate-receiver-vg.sh, tests/msleep.c, tests/receive-emptyconnect.sh, tests/receive.c, tests/receiver-abort.sh, tests/selftest_receive_watchdog.sh, tests/send.c, tests/test-framework.sh, tests/tls-basic-anon.sh, tests/tls-basic-certchain.sh, tests/tls-basic-certvalid-mixed.sh, tests/tls-basic-certvalid.sh, tests/tls-basic-fingerprint.sh, tests/tls-basic-realistic.sh, tests/tls-basic-tlscommand-ciphers.sh, tests/tls-basic-tlscommand.sh, tests/tls-basic-vg.sh, tests/tls-basic-wildcard.sh, tests/tls-basic.sh, tests/tls-missing-param-receiver.sh, tests/tls-receiver-abort.sh, tests/tls-wrong-permittedPeer.sh, tests/tls-wrong-signedcert.sh
- removed long options from receive send utilities (Not supported on AIX).
- added checks for existing commands in some tests.
- added msleep utility from rsyslog (sleep, timeout etc. not supported on AIX).
closes: https://github.com/rsyslog/librelp/issues/228
=> testbench: Added compatiblity to run on AIX

src/tcp.c, tests/basic-sessionbreak-vg.sh, tests/known_issues.supp
An exit call was left from commit 6555545c4ebe9afe9259b15c176fd81eeecc93f4
which could cause unexpected results if gnutls gnutls_record_recv
returned an error.
closes: https://github.com/rsyslog/librelp/issues/230
=> gnutls: Fix relpTcpRcv error handler, should return error now.

src/relpsess.c, src/tcp.c, tests/receiver-abort.sh, tests/test-framework.sh, tests/tls-basic-realistic.sh, tests/tls-receiver-abort.sh
- avoid invalid dbgprint calls
- avoid double free in relpTcpDestruct (if called twice).
- add debug output into relpTcpRcv
- move receive buffer in relpSessRcvData to dyn memory (Stack before)
- AIX: in relpTcpRcv we need to set RETRY_recv if errno is 0
=> librelp hardening: Fix multiple minor issues causing debugging trouble

src/tcp.c
If TLS is not active, a check on a not existing TLS session could be made for TCP retry.
closes: https://github.com/rsyslog/librelp/issues/240
=> TCP: relpTcpGetRtryDirection onyl needs to check direction if TLS active

src/tcp.c, tests/tls-basic-tlscommand-ciphers.sh, tests/tls-basic-tlscommand.sh, tests/tls-wrong-permittedPeer.sh, tests/tls-wrong-signedcert.sh
- Add handling for other ERRNO codes in tcp.c for AIX
- Fix commands in some tests that were not correctly handled on AIX.
=> Fixes network issues on AIX

src/relp.c
Forward the return code of ```relpEngineSetTLSLib()``` to ```relpEngineSetTLSLibByName()```.
Current situation: In case librelp is compiled without openssl support but openssl is requested from the user side, then librelp silently switches to the default tls driver(gnutls).
=> Forward return code from relpEngineSetTLSLib to relpEngineSetTLSLibName

src/relp.c
In case ```pThis == NULL``` condition is true at line https://github.com/rsyslog/librelp/blob/master/src/relp.c#L345 , ```pThis->dbgprint(...)``` would cause unexpected behavior.
=> Make relpEngineSetTLSLib debug safe

src/tcp.c
There are undefined reference to CRYPTO_set_id_callback if system use openssl 1.1
=> undefined reference to CRYPTO_set_id_callback

src/offers.c, src/tcp.c
I've executed covscan analysis on the librelp component, which detected a list of potential defects. I was able to fix most of them but the 3rd warning seems like a false positive to me. Let me know if there is a way to make such a warning disappear.
```
librelp-1.9.0/src/offers.c:221: buffer_size_warning: Calling "strncpy" with a maximum size argument of 256 bytes on destination array "pThis->szVal" of size 256 bytes might leave the destination string unterminated.
```
```
librelp-1.9.0/src/offers.c:266: buffer_size_warning: Calling "strncpy" with a maximum size argument of 33 bytes on destination array "pThis->szName" of size 33 bytes might leave the destination string unterminated.
```
```
librelp-1.9.0/src/relpsrv.c:409: alloc_arg: "relpTcpConstruct" allocates memory that is stored …
```
=> Fix warnings reported by covscan

src/relpsess.c, src/relpsess.h
During the initial librelp implementation it was thought about an auto-retry feature (whatever that means). Variable bAutoRetry was created to control that behaviour. It's default was 0 (inactive). Some code has been written to evaluate that variable and act accordingly. However, no setter method for this variable was created and it was also nowhere changed from the default value of zero. As such, the code activated by it was never used.
This patch now removes both the variable and the few code lines accessing it. This will have no effect, as the code was never used.
closes: https://github.com/rsyslog/librelp/issues/223
replaces: https://github.com/rsyslog/librelp/pull/234
=> code cleanup

src/tcp.c
When --enable-tls=no and --enable-tls-openssl=yes, the following
compiler errors are reported:
```
| ../../git/src/tcp.c:3765:1: error: no previous declaration for 'relpTcpGetRtryDirection_gtls' [-Werror=missing-declarations]
|  3765 | relpTcpGetRtryDirection_gtls(LIBRELP_ATTR_UNUSED relpTcp_t *const pThis)
|       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../../git/src/tcp.c:3583:1: error: 'relpTcpChkPeerName' defined but not used [-Werror=unused-function]
|  3583 | relpTcpChkPeerName(NOTLS_UNUSED relpTcp_t *const pThis, NOTLS_UNUSED void* cert)
|       | ^~~~~~~~~~~~~~~~~~
```
Fix these by:
1. Add static on the openssl path for relpTcpGetRtryDirection_gtls.
2. Move the relpTcpChkPeerName forward declaration to another ifdef
leg.
3. Wrap relpTcpChkPeerName in gnutls-based ifdef.
4. Remove …
=> tcp: fix some compiler warnings with enable-tls-openssl

.github/workflows/run_centos_8.yml, .github/workflows/run_fedora_36.yml
we used older ubuntu versions as base for our containers, these versions are no longer available in github actions. As such, we upgraded. Has no effect on testbench as we execute everything in container environment and container remains the same.
=> CI: upgrading to newer ubuntu version as required by github

configure.ac
- Fixes issue #256 
Compiler does not inline any functions when using debug optimization (-Og). Hence, remove -Winline flag when compiling with debug optimization.
=> Fix function inline errors in debug optimization (-Og)

src/tcp.c
ENGINE_cleanup is deprecated as of OpenSSL 1.1.0, and may not be available with 3.0 and OPENSSL_NO_ENGINE (e.g. Fedora 41 and RHEL 10).
=> tcp: avoid deprecated ENGINE_cleanup
